PORT: 9090
BUFFER_SIZE: 1024
ENCODING: utf-8
MAX_CONNECTIONS: 5
DIR_MODEL_PREPROCESSING: "../onnx/u2netp.onnx"
ROOT_DIR: "/home/server"

COMMAND:
  0x01: request_classification
  0x02: response_classification
  0x03: stop_classification
  0x04: stop_response
  0x05: request_download
  0x06: response_download
  0x07: request_model_select
  0x08: response_model_select
  0x09: request_current_model
  0x10: response_current_model
  0x11: request_model_delete
  0x12: response_model_delete
  0x28: close_connection
  0x29: error_message
