PORT: 9090
BUFFER_SIZE: 1024
ENCODING: utf-8
MAX_CONNECTIONS: 5

COMMAND:
  0x01: request_classification
  0x02: response_classification
  0x03: stop_classification
  0x04: request_download
  0x05: response_download
  0x06: request_model_select
  0x07: response_model_select
  0x08: request_current_model
  0x09: response_current_model
  0x10: request_model_change
  0x11: response_model_change
  0x12: request_model_delete
  0x13: response_model_delete
  0x28: close_connection
  0x29: error_message
