PORT: 9090
IP: 192.168.0.40
BUFFER_SIZE: 1024
ENCODING: utf-8
MAX_CONNECTIONS: 5
DIR_MODEL_DETECTION: "weights"
DIR_IMG: "img"

COMMAND:
  0x01: request_classification
  0x02: response_classification
  0x03: stop_classification
  0x04: stop_response
  0x20: request_download
  0x21: response_download
  0x22: request_current_model
  0x23: response_current_model
  0x24: request_list_model
  0x25: response_list_model
  0x26: model_change_request
  0x27: model_change_response
  0x28: request_delete_model
  0x29: response_delete_model
  0x30: request_change_img_folder
  0x31: response_change_img_folder
  0x32: request_current_img_folder
  0x33: response_current_img_folder

CORRESPONDING_COMMAND:
  0x01: 0x02
  0x03: 0x04
  0x20: 0x21
  0x22: 0x23
  0x24: 0x25
  0x26: 0x27
  0x28: 0x29
  0x30: 0x31
  0x32: 0x33

ERROR_CODE:
  no_error: 0
  invalid_message: 1
  resource_not_found: 2
  not_exist_command: 3
  timeout: 4